### ISSUE TITLE
Documentation missing.

### ISSUE THREAD

**Issue by dreirund** [Eroldin/vssh#1]
Ahoj,

I cannot find any documentation within this package.

I wish to know what it does, how it does the things, how to use it, how to configure, etc.

Please write documentation.

Regards!

**Comment by Eroldin** [comment]
A readme file has been created with a simple explanation. I hope this is sufficient?

**Comment by dreirund** [comment]
It reads more like spreading words on how cool the software is and for my taste it misses exact technical information and information on arguments to `vssh`, but better than nothing.

Thanks!
